// **********************************************************************
//
// Copyright (c) 2003-2011 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.4.2
//
// <auto-generated>
//
// Generated from file `_CounterServiceOperationsNC.java'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package sce.demo;

public interface _CounterServiceOperationsNC
{
    int incr();

    int decr();

    int get();

    void set(int num);
}
