// **********************************************************************
//
// Copyright (c) 2003-2011 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.4.2
//
// <auto-generated>
//
// Generated from file `_CounterServiceOperations.java'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package sce.demo;

public interface _CounterServiceOperations
{
    int incr(Ice.Current __current);

    int decr(Ice.Current __current);

    int get(Ice.Current __current);

    void set(int num, Ice.Current __current);
}
