// **********************************************************************
//
// Copyright (c) 2003-2011 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.4.2
//
// <auto-generated>
//
// Generated from file `_CounterServiceDel.java'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package sce.demo;

public interface _CounterServiceDel extends Ice._ObjectDel
{
    int incr(java.util.Map<String, String> __ctx)
        throws IceInternal.LocalExceptionWrapper;

    int decr(java.util.Map<String, String> __ctx)
        throws IceInternal.LocalExceptionWrapper;

    int get(java.util.Map<String, String> __ctx)
        throws IceInternal.LocalExceptionWrapper;

    void set(int num, java.util.Map<String, String> __ctx)
        throws IceInternal.LocalExceptionWrapper;
}
